
# Convert models in keras-models.txt
./convert-keras-models.sh -x -p 3 -f keras-models.txt

# Build the projects generated by keras-to-hls script.
# Remove parameter -s to disable synthesis. -p controls the number of parallel tasks -c do only the c++ compilation
#./build-prj.sh

./build-prj.sh -c

# Clean-up at the end
#./cleanup.sh
